kind: pipeline
type: digitalocean
name: yugo-deploy

token:
  from_secret: DOCR_TOKEN

server:
  image: docker-20-04
  size: s-2vcpu-4gb
  region: nyc1

steps:
  - name: docker-build-api
    image: plugins/docker
    settings:
      registry: registry.digitalocean.com
      username:
        from_secret: DOCR_TOKEN
      password:
        from_secret: DOCR_TOKEN
      repo: registry.digitalocean.com/yugo-builds/api
      dockerfile: Dockerfile.api
      context: .
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

  - name: docker-build-henchman
    image: plugins/docker
    settings:
      registry: registry.digitalocean.com
      username:
        from_secret: DOCR_TOKEN
      password:
        from_secret: DOCR_TOKEN
      repo: registry.digitalocean.com/yugo-builds/henchman
      dockerfile: Dockerfile.henchmen
      context: .
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

  - name: docker-build-backoffice
    image: plugins/docker
    settings:
      registry: registry.digitalocean.com
      username:
        from_secret: DOCR_TOKEN
      password:
        from_secret: DOCR_TOKEN
      repo: registry.digitalocean.com/yugo-builds/backoffice
      dockerfile: apps/backoffice/Dockerfile
      context: .
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

trigger:
  event:
    - push
  branch:
    - dev
