FROM node:22-bookworm-slim

WORKDIR /usr/src/app

COPY --from=yugo/builder /usr/src/app /usr/src/app

RUN corepack enable && corepack prepare yarn@4.3.1 --activate \
  && yarn workspaces focus --production --all

USER node

CMD ["node", "apps/cli/dist/main.js"]