FROM node:22-alpine AS base
RUN corepack enable

FROM base AS build
WORKDIR /app
COPY package.json yarn.lock .yarnrc.yml ./
COPY packages ./packages
COPY apps ./apps

RUN yarn install --immutable
RUN yarn turbo run build --filter=@yugo/henchmen

FROM base AS deps
WORKDIR /app
COPY package.json yarn.lock .yarnrc.yml ./
COPY packages ./packages
COPY apps ./apps
RUN yarn workspaces focus @yugo/henchmen --production

FROM base AS production
WORKDIR /app
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/packages ./packages
COPY --from=build /app/apps/henchmen/dist ./apps/henchmen/dist
COPY --from=build /app/apps/henchmen/package.json ./apps/henchmen/package.json
COPY migrations ./migrations

EXPOSE 4502
CMD ["node", "apps/henchmen/dist/main.js"]
