version: "3.9"

networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=tech@evyugo.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configs/traefik/acme.json:/etc/traefik/acme.json"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.rule=Host(`traefik.evyugo.com`)"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.40
    env_file:
      - /home/officebot/yugo/envs/.env.watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/officebot/.docker/config.json:/config.json:ro
    networks:
      - traefik

  api:
    image: registry.digitalocean.com/yugo-builds/api:latest
    container_name: api
    restart: always
    env_file: envs/.env.api
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.evyugo.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=4500"

  henchman:
    image: registry.digitalocean.com/yugo-builds/henchman:latest
    container_name: henchman
    restart: always
    env_file: envs/.env.henchman
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backoffice:
    image: registry.digitalocean.com/yugo-builds/backoffice:latest
    container_name: backoffice
    restart: always
    env_file: envs/.env.backoffice
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backoffice.rule=Host(`admin.evyugo.com`)"
      - "traefik.http.routers.backoffice.entrypoints=websecure"
      - "traefik.http.routers.backoffice.tls=true"
      - "traefik.http.routers.backoffice.tls.certresolver=letsencrypt"
      - "traefik.http.services.backoffice.loadbalancer.server.port=3000"

